app = "washbuddy"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[services]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[checks]
  [checks.http]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "2s"
    type = "http"
