app = "washbuddy"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sh -c 'cd /app && python manage.py migrate'"

[vm]
  size = "shared-cpu-1x"
  memory_mb = 512

[services]
  internal_port = 8000
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
