# Generated by Django 5.1.6 on 2025-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bounty_limit_override',
            field=models.BooleanField(default=False, help_text='Override the bounty limit for this user.'),
        ),
    ]
