# Generated by Django 5.1.6 on 2025-02-18 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_type_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarWashAmenityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_wash_mappings', to='carwash_filter.amenity')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_mappings', to='carwash.carwash')),
            ],
            options={
                'verbose_name': 'Car Wash Amenity Mapping',
                'verbose_name_plural': 'Car Wash Amenity Mappings',
                'unique_together': {('car_wash', 'amenity')},
            },
        ),
        migrations.CreateModel(
            name='CarWashWashTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_type_mappings', to='carwash.carwash')),
                ('wash_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_wash_mappings', to='carwash_filter.washtype')),
            ],
            options={
                'verbose_name': 'Car Wash Type Mapping',
                'verbose_name_plural': 'Car Wash Type Mappings',
                'unique_together': {('car_wash', 'wash_type')},
            },
        ),
    ]
