# Generated by Django 5.1.6 on 2025-03-03 17:26

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('automatic', 'Automatic Car Wash'), ('selfservice', 'Self Service Car Wash')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('subclass', models.CharField(choices=[('Clean', 'Clean'), ('Polish', 'Polish'), ('Shine/Dry', 'Shine/Dry')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('automatic', 'Automatic Car Wash'), ('selfservice', 'Self Service Car Wash')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmenityCarWashMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_wash_name', models.CharField(db_index=True, max_length=255)),
                ('car_wash_address', models.CharField(max_length=255)),
                ('formatted_address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('reviews_count', models.IntegerField(default=0)),
                ('reviews_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=8, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('automatic_car_wash', models.BooleanField()),
                ('self_service_car_wash', models.BooleanField()),
                ('open_24_hours', models.BooleanField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(related_name='car_washes', through='carwash.AmenityCarWashMapping', to='carwash.amenity')),
            ],
        ),
        migrations.AddField(
            model_name='amenitycarwashmapping',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash'),
        ),
        migrations.CreateModel(
            name='CarWashImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Image type must be at least 0'), django.core.validators.MaxValueValidator(7, 'Image type must be at most 7')])),
                ('image_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='CarWashWashTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash')),
                ('wash_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.washtype')),
            ],
            options={
                'unique_together': {('car_wash', 'wash_type')},
            },
        ),
        migrations.AddField(
            model_name='carwash',
            name='wash_types',
            field=models.ManyToManyField(related_name='car_washes', through='carwash.CarWashWashTypeMapping', to='carwash.washtype'),
        ),
        migrations.AlterUniqueTogether(
            name='amenitycarwashmapping',
            unique_together={('car_wash', 'amenity')},
        ),
        migrations.CreateModel(
            name='CarWashOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Day must be at least 0'), django.core.validators.MaxValueValidator(6, 'Day must be at most 6')])),
                ('is_closed', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash')),
            ],
            options={
                'indexes': [models.Index(fields=['day_of_week', 'is_closed'], name='carwash_car_day_of__3fd73d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('closing_time__isnull', True), ('is_closed', True), ('opening_time__isnull', True)), models.Q(('closing_time__isnull', False), ('is_closed', False), ('opening_time__isnull', False)), _connector='OR'), name='check_opening_closing_times')],
                'unique_together': {('car_wash', 'day_of_week')},
            },
        ),
        migrations.AddIndex(
            model_name='carwash',
            index=models.Index(fields=['automatic_car_wash', 'self_service_car_wash'], name='carwash_car_automat_0b761a_idx'),
        ),
        migrations.AddIndex(
            model_name='carwash',
            index=models.Index(fields=['open_24_hours'], name='carwash_car_open_24_0171ef_idx'),
        ),
    ]
