# Generated by Django 5.1.6 on 2025-02-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_wash_name', models.CharField(max_length=255)),
                ('car_wash_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('reviews_count', models.IntegerField()),
                ('reviews_average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('automatic_car_wash', models.BooleanField()),
                ('self_service_car_wash', models.BooleanField()),
                ('open_24_hours', models.BooleanField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarWashImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=255)),
                ('image_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='CarWashOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('closing_time__isnull', True), ('is_closed', True), ('opening_time__isnull', True)), models.Q(('closing_time__isnull', False), ('is_closed', False), ('opening_time__isnull', False)), _connector='OR'), name='check_opening_closing_times')],
                'unique_together': {('car_wash', 'day_of_week')},
            },
        ),
    ]
