# Generated by Django 5.1.6 on 2025-03-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwash',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='longitude',
        ),
    ]
