# Generated by Django 5.1.6 on 2025-02-21 14:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('automatic', 'Automatic Car Wash'), ('selfservice', 'Self Service Car Wash')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('automatic', 'Automatic Car Wash'), ('selfservice', 'Self Service Car Wash')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carwash',
            name='reviews_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carwashimage',
            name='image_type',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Image type must be at least 0'), django.core.validators.MaxValueValidator(7, 'Image type must be at most 7')]),
        ),
        migrations.AlterField(
            model_name='carwashoperatinghours',
            name='day_of_week',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Day must be at least 0'), django.core.validators.MaxValueValidator(6, 'Day must be at most 6')]),
        ),
        migrations.CreateModel(
            name='CarWashAmenityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.amenity')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash')),
            ],
            options={
                'unique_together': {('car_wash', 'amenity')},
            },
        ),
        migrations.CreateModel(
            name='CarWashWashTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carwash')),
                ('wash_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.washtype')),
            ],
            options={
                'unique_together': {('car_wash', 'wash_type')},
            },
        ),
    ]
