# Generated by Django 5.1.6 on 2025-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_amenity_washtype_alter_carwash_reviews_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='washtype',
            name='subclass',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Polish', 'Polish'), ('Shine/Dry', 'Shine/Dry')], default='Clean', max_length=20),
        ),
    ]
