# Generated by Django 5.1.6 on 2025-02-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_rename_carwashamenitymapping_amenitycarwashmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='amenities',
            field=models.ManyToManyField(related_name='car_washes', through='carwash.AmenityCarWashMapping', to='carwash.amenity'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='wash_types',
            field=models.ManyToManyField(related_name='car_washes', through='carwash.CarWashWashTypeMapping', to='carwash.washtype'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('automatic', 'Automatic Car Wash'), ('selfservice', 'Self Service Car Wash')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='car_wash_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='washtype',
            name='category',
            field=models.CharField(choices=[('automatic', 'Automatic Car Wash'), ('selfservice', 'Self Service Car Wash')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='washtype',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='washtype',
            name='subclass',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Polish', 'Polish'), ('Shine/Dry', 'Shine/Dry')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='carwash',
            index=models.Index(fields=['automatic_car_wash', 'self_service_car_wash'], name='carwash_car_automat_0b761a_idx'),
        ),
        migrations.AddIndex(
            model_name='carwash',
            index=models.Index(fields=['open_24_hours'], name='carwash_car_open_24_0171ef_idx'),
        ),
        migrations.AddIndex(
            model_name='carwashoperatinghours',
            index=models.Index(fields=['day_of_week', 'is_closed'], name='carwash_car_day_of__3fd73d_idx'),
        ),
    ]
