# Generated by Django 5.1.6 on 2025-03-03 22:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_carwash_city_carwash_country_carwash_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwash',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='car_wash_address',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='carwash',
            name='longitude',
        ),
        migrations.AddField(
            model_name='carwash',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
