# Generated by Django 5.1.6 on 2025-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0008_add_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitycarwashmapping',
            name='price_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carwashwashtypemapping',
            name='price_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
