# Generated by Django 5.1.6 on 2025-03-13 05:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0009_amenitycarwashmapping_price_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='carwash',
            options={'verbose_name': 'Car Wash', 'verbose_name_plural': 'Car Washes'},
        ),
        migrations.AddField(
            model_name='carwash',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carwash',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amenitycarwashmapping',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_wash_mapping', to='carwash.amenity'),
        ),
        migrations.AlterField(
            model_name='amenitycarwashmapping',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_mapping', to='carwash.carwash'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='reviews_average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carwashimage',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carwash.carwash'),
        ),
        migrations.AlterField(
            model_name='carwashoperatinghours',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='carwash.carwash'),
        ),
        migrations.AlterField(
            model_name='carwashwashtypemapping',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_type_mapping', to='carwash.carwash'),
        ),
        migrations.AlterField(
            model_name='carwashwashtypemapping',
            name='wash_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_wash_mapping', to='carwash.washtype'),
        ),
    ]
