# Generated by Django 5.1.6 on 2025-03-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0010_alter_amenity_options_alter_carwash_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenitycarwashmapping',
            name='price_rate',
        ),
        migrations.RemoveField(
            model_name='carwashwashtypemapping',
            name='price_rate',
        ),
        migrations.CreateModel(
            name='CarWashPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(related_name='packages', to='carwash.amenity')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='carwash.carwash')),
                ('wash_types', models.ManyToManyField(related_name='packages', to='carwash.washtype')),
            ],
        ),
    ]
