# Generated by Django 5.1.6 on 2025-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0011_remove_amenitycarwashmapping_price_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashpackage',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='packages', to='carwash.amenity'),
        ),
        migrations.AlterField(
            model_name='carwashpackage',
            name='wash_types',
            field=models.ManyToManyField(blank=True, related_name='packages', to='carwash.washtype'),
        ),
    ]
