# Generated by Django 5.1.6 on 2025-03-19 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0012_alter_carwashpackage_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='amenity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='amenitycarwashmapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='amenitycarwashmapping',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='amenitycarwashmapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='carwash',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashimage',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='carwashimage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashoperatinghours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carwashoperatinghours',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashoperatinghours',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='carwashoperatinghours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carwashoperatinghours',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashwashtypemapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='carwashwashtypemapping',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='carwashwashtypemapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='washtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile'),
        ),
        migrations.AddField(
            model_name='washtype',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='washtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile'),
        ),
    ]
