# Generated by Django 5.1.6 on 2025-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0013_amenity_created_by_amenity_status_amenity_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashimage',
            name='image_key',
        ),
        migrations.AddField(
            model_name='carwashimage',
            name='image_url',
            field=models.URLField(default='', max_length=500, verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carwashimage',
            name='image_type',
            field=models.CharField(choices=[('Menu', 'Menu'), ('Station', 'Station'), ('Exterior', 'Exterior'), ('Interior', 'Interior')], max_length=100),
        ),
    ]
