# Generated by Django 5.1.6 on 2025-03-27 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0014_remove_carwashimage_image_key_carwashimage_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100)),
                ('user_metadata', models.JSONField()),
                ('comment', models.TextField()),
                ('overall_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating must be at least 0'), django.core.validators.MaxValueValidator(5, 'Rating must be at most 5')])),
                ('wash_quality_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating must be at least 0'), django.core.validators.MaxValueValidator(5, 'Rating must be at most 5')])),
                ('price_value_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating must be at least 0'), django.core.validators.MaxValueValidator(5, 'Rating must be at most 5')])),
                ('facility_cleanliness_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating must be at least 0'), django.core.validators.MaxValueValidator(5, 'Rating must be at most 5')])),
                ('customer_service_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating must be at least 0'), django.core.validators.MaxValueValidator(5, 'Rating must be at most 5')])),
                ('amenities_extra_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating must be at least 0'), django.core.validators.MaxValueValidator(5, 'Rating must be at most 5')])),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='carwash.carwash')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarWashReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('carwash_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carwash.carwashreview')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
