# Generated by Django 5.1.6 on 2025-04-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0016_remove_carwash_wash_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashpackage',
            name='category',
            field=models.CharField(choices=[('automatic', 'Automatic Car Wash'), ('selfservice', 'Self Service Car Wash')], default='automatic', max_length=20),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='rate_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
