# Generated by Django 5.1.6 on 2025-04-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0016_remove_carwash_amenities_remove_carwash_wash_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carwashwashtypemapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='carwashwashtypemapping',
            name='car_wash',
        ),
        migrations.RemoveField(
            model_name='carwashwashtypemapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='carwashwashtypemapping',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='carwashwashtypemapping',
            name='wash_type',
        ),
        migrations.DeleteModel(
            name='AmenityCarWashMapping',
        ),
        migrations.DeleteModel(
            name='CarWashWashTypeMapping',
        ),
    ]
