# Generated by Django 5.1.6 on 2025-04-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0017_carwashpackage_category_carwashpackage_rate_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashimage',
            name='image_type',
            field=models.CharField(choices=[('Site', 'Site'), ('Amenities', 'Amenities'), ('Menu', 'Menu'), ('Interior', 'Interior'), ('Exterior', 'Exterior')], max_length=100),
        ),
    ]
