# Generated by Django 5.1.6 on 2025-04-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0017_carwashpackage_category_carwashpackage_rate_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashimage',
            name='image_type',
            field=models.CharField(choices=[('Site', 'Site'), ('Amenities', 'Amenities'), ('Menu', 'Menu'), ('Interior', 'Interior'), ('Exterior', 'Exterior')], max_length=100),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_type', models.CharField(choices=[('TIME_DEPENDENT', 'Time Dependent'), ('ONE_TIME', 'One Time'), ('GEOGRAPHICAL', 'Geographical')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('radius_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='carwash.carwashpackage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CarWashCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_metadata', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='carwash.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', False), ('offer_type', 'TIME_DEPENDENT'), ('start_time__isnull', False)), models.Q(('end_time__isnull', True), ('offer_type', 'ONE_TIME'), ('start_time__isnull', True)), models.Q(('offer_type', 'GEOGRAPHICAL'), ('radius_miles__isnull', False)), _connector='OR'), name='check_offer_type_constraints'),
        ),
    ]
