# Generated by Django 5.1.6 on 2025-04-18 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0018_alter_carwashimage_image_type_offer_carwashcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashcode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='carwashcode',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='carwashcode',
            name='used_by_metadata',
        ),
        migrations.CreateModel(
            name='CarWashCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100)),
                ('user_metadata', models.JSONField()),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='carwash.carwashcode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to='carwash.userprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to='carwash.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
