# Generated by Django 5.1.6 on 2025-05-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0018_alter_carwashimage_image_type'),
        ('carwash', '0021_payment_carwash_code'),
    ]

    operations = [
    ]
