# Generated by Django 5.1.6 on 2025-05-02 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0022_alter_amenity_created_by_alter_amenity_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carwashcode',
            unique_together={('code', 'offer')},
        ),
        migrations.AddConstraint(
            model_name='carwashcode',
            constraint=models.UniqueConstraint(fields=('code', 'offer'), name='unique_code_per_offer'),
        ),
    ]
