# Generated by Django 5.1.6 on 2025-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0022_merge_20250502_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashreview',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
