# Generated by Django 5.1.6 on 2025-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0023_alter_carwashcode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashcode',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
