# Generated by Django 5.1.6 on 2025-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0024_alter_carwashcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carwashcode',
            name='user_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
