# Generated by Django 5.1.6 on 2025-05-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0025_carwashcode_used_at_carwashcode_user_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarWashCodeUsage',
        ),
    ]
