# Generated by Django 5.1.6 on 2025-06-11 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0026_delete_carwashcodeusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashcode',
            name='user_metadata',
        ),
        migrations.RemoveField(
            model_name='carwashreview',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='carwashreview',
            name='user_metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_email',
        ),
        migrations.AddField(
            model_name='carwash',
            name='active_bounty',
            field=models.BooleanField(default=False, verbose_name='Active Bounty'),
        ),
        migrations.AddField(
            model_name='carwashcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carwashreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CarWashUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('NOT_STARTED', 'Not Started'), ('CANCELLED', 'Cancelled'), ('APPROVAL', 'Approval'), ('REQUEST', 'Request'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation'), ('CLOSURE', 'Closure'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=100)),
                ('proposed_changes', models.JSONField()),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='carwash.carwash')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_wash_update_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Wash Update Request',
                'verbose_name_plural': 'Car Wash Update Requests',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
