# Generated by Django 5.1.6 on 2025-06-14 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0027_remove_carwashcode_user_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashupdaterequest',
            name='car_wash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='carwash.carwash'),
        ),
        migrations.AddField(
            model_name='carwashupdaterequest',
            name='payment_handle',
            field=models.CharField(max_length=250)
        ),
        migrations.AddField(
            model_name='carwashupdaterequest',
            name='payment_method',
            field=models.CharField(max_length=250)
        ),
        migrations.AddField(
            model_name='carwashupdaterequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carwashupdaterequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carwashupdaterequest',
            name='payouts_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
