# Generated by Django 5.1.6 on 2025-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0028_alter_carwashupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashupdaterequest',
            name='is_bounty_claim',
            field=models.BooleanField(default=False, verbose_name='Is Bounty Claim'),
        ),
        migrations.AlterField(
            model_name='carwashupdaterequest',
            name='payment_handle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='carwashupdaterequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='carwashupdaterequest',
            name='payouts_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=50),
        ),
    ]
