name: Backend Build and Deploy Workflow

on:
  workflow_call:
    secrets:
      ALL_SECRETS:
        required: true
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Load All Secrets into Environment
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ secrets.ALL_SECRETS || toJSON(secrets) }}

      - name: Debug Environment Variables
        run: env

      - name: Setup Python (Backend)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (Backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend

      - name: Run Migrations (Backend)
        run: python manage.py migrate --noinput
        working-directory: backend

      - name: Create Admin Superuser (Backend)
        run: python manage.py create_admin
        working-directory: backend

      - name: Collect static files (Backend)
        run: python manage.py collectstatic --noinput
        working-directory: backend

      - name: Deploy to Vercel (Backend)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
        run: npx vercel --prod --token $VERCEL_TOKEN
        working-directory: backend