name: Backend Build and Deploy Workflow

on:
  workflow_call:
    secrets:
      ALL_SECRETS:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_BACKEND_PROJECT_ID:
        required: true
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/osgeo/gdal:alpine-small-3.10.2
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Load All Secrets into Environment
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ secrets.ALL_SECRETS || toJSON(secrets) }}

      - name: Debug Environment Variables
        run: env | sort

      - name: Install Required System Packages (Minimal)
        run: |
          apk update && apk add --no-cache \
            g++ \
            python3 \
            python3-dev \
            py3-pip \
            proj \
            proj-dev \
            libstdc++

      - name: Install Python and dependencies
        run: |
          python3 -m venv /opt/venv
          source /opt/venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
        working-directory: backend

      - name: Run Migrations (Backend)
        run: python manage.py migrate --noinput
        working-directory: backend

      - name: Create Admin Superuser (Backend)
        run: python manage.py create_admin || echo "Admin already exists, skipping..."
        working-directory: backend

      - name: Collect Static Files (Backend)
        run: python manage.py collectstatic --noinput
        working-directory: backend
