name: Backend Build and Deploy Workflow

on:
  workflow_call:
    secrets:
      ALL_SECRETS:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_BACKEND_PROJECT_ID:
        required: true
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Load All Secrets into Environment
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ secrets.ALL_SECRETS || toJSON(secrets) }}

      - name: Debug Environment Variables
        run: env | sort

      - name: Build Docker Image from Repository `Dockerfile`
        run: docker build -t washbuddy-backend -f Dockerfile .
        working-directory: backend

      - name: Run Django Migrations, Create Superuser, and Collect Static Files in One Container
        run: |
          docker run --rm \
            washbuddy-backend sh -c "
            python manage.py migrate --noinput &&
            python manage.py create_admin || echo 'Admin already exists, skipping...' &&
            python manage.py collectstatic --noinput"
        working-directory: backend
