name: Backend Build and Deploy Workflow

on:
  workflow_call:
    secrets:
      ALL_SECRETS:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_BACKEND_PROJECT_ID:
        required: true
      FLY_API_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Load All Secrets into Environment
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ secrets.ALL_SECRETS || toJSON(secrets) }}

      - name: Debug Environment Variables
        run: env | sort

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Django App to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --config fly.toml
        working-directory: backend