name: Backend Build and Deploy Workflow

on:
  workflow_call:
    secrets:
      ALL_SECRETS:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_BACKEND_PROJECT_ID:
        required: true
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: geographica/gdal-python
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Load All Secrets into Environment
        if: env.ALL_SECRETS != ''
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ secrets.ALL_SECRETS }}

      - name: Debug Environment Variables
        run: env | sort

      - name: Install dependencies (Backend)
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Migrations (Backend)
        run: cd backend && python manage.py migrate --noinput

      - name: Create Admin Superuser (Backend)
        run: cd backend && python manage.py create_admin || echo "Admin already exists, skipping..."

      - name: Collect Static Files (Backend)
        run: cd backend && python manage.py collectstatic --noinput
