name: Backend Build and Deploy Workflow

on:
  workflow_call:
    secrets:
      ALL_SECRETS:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_BACKEND_PROJECT_ID:
        required: true
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: postgis/postgis:16-3.4
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Load All Secrets into Environment
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ secrets.ALL_SECRETS || toJSON(secrets) }}

      - name: Debug Environment Variables
        run: env | sort

      - name: Install Minimal System Dependencies
        run: |
          apt-get update && apt-get install -y \
            python3 python3-dev python3-pip libpq-dev

      - name: Set Up Python Virtual Environment
        run: |
          python3 -m venv /opt/venv
          echo "VIRTUAL_ENV=/opt/venv" >> $GITHUB_ENV
          echo "/opt/venv/bin" >> $GITHUB_PATH

      - name: Install Python and dependencies
        run: pip install --no-cache-dir -r requirements.txt
        working-directory: backend

      - name: Run Migrations (Backend)
        run: python manage.py migrate --noinput
        working-directory: backend

      - name: Create Admin Superuser (Backend)
        run: python manage.py create_admin || echo "Admin already exists, skipping..."
        working-directory: backend

      - name: Collect Static Files (Backend)
        run: python manage.py collectstatic --noinput
        working-directory: backend
