name: Monorepo CI/CD with Conditional Deploys

on:
  push:
    branches:
      - master

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      deploy-landing: ${{ steps.check_landing.outputs.deploy-landing }}
      deploy-frontend: ${{ steps.check_frontend.outputs.deploy-frontend }}
      deploy-backend: ${{ steps.check_backend.outputs.deploy-backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get base branch reference
        id: get_base
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          else
            echo "BASE_BRANCH=origin/master" >> $GITHUB_ENV
          fi

      - name: Fetch latest from master
        run: git fetch origin master --depth=1

      - name: Check for changes in "landing"
        id: check_landing
        run: |
          if git diff --quiet origin/master HEAD -- landing/; then
            echo "deploy-landing=false" >> $GITHUB_OUTPUT
          else
            echo "deploy-landing=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in "frontend"
        id: check_frontend
        run: |
          if git diff --quiet origin/master HEAD -- frontend/; then
            echo "deploy-frontend=false" >> $GITHUB_OUTPUT
          else
            echo "deploy-frontend=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in "backend"
        id: check_backend
        run: |
          if git diff --quiet origin/master HEAD -- backend/; then
            echo "deploy-backend=false" >> $GITHUB_OUTPUT
          else
            echo "deploy-backend=true" >> $GITHUB_OUTPUT
          fi

  landing:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.deploy-landing == 'true' }}
    uses: ./.github/workflows/landing-build.yml

  frontend:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.deploy-frontend == 'true' }}
    uses: ./.github/workflows/frontend-build.yml

  backend:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.deploy-backend == 'true' }}
    uses: ./.github/workflows/backend-build.yml