name: Frontend Build and Deploy Workflow

on:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_FRONTEND_PROJECT_ID:
        required: true
      NEXT_PUBLIC_SUPABASE_URL:
        required: true
      NEXT_PUBLIC_SUPABASE_ANON_KEY:
        required: true
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (Frontend)
        run: npm ci
        working-directory: frontend

      - name: Publish Storybook to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend

      - name: Build the project (Frontend)
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build --force
        working-directory: frontend

      - name: Deploy to Vercel (Frontend)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
        run: npx vercel --prod --token $VERCEL_TOKEN
        working-directory: frontend
