name: Landing Build and Deploy Workflow

on:
  release:
    types: [published]

jobs:
  landing:
    uses: ./.github/workflows/landing-build.yml
    environment: production
    with:
      environment: 'production'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_LANDING_PROJECT_ID: ${{ secrets.VERCEL_LANDING_PROJECT_ID }}
